### ISSUE TITLE
Disposal lifecycle of sockets

### ISSUE THREAD

**Issue by bender2k14** [jmarnold/EmbeddedMail#4]
The [`Dispose` method of `EmbeddedSmtpServer`](https://github.com/jmarnold/EmbeddedMail/blob/master/src/EmbeddedMail/EmbeddedSmtpServer.cs#L123) is implemented as
```
public void Dispose()
{
    Stop();
    // I don't grok the disposal lifecycle for the sockets yet
    Listener.Stop();

    _sessions.Each(x => x.Dispose());
}
```

but I think it should be more like
```
public void Dispose()
{
    Stop();
    _sessions.Each(x => x.Dispose());
    Listener.Stop();
}
```

I have two reasons for this: one theoretical and one practical.

The theoretical reason is that objects should be disposed in the reverse order in which they are created, and `Listener` is created before each session.  In fact (from the point of view of `EmbeddedSmtpServer`), [`Listener` creates the sockets](https://github.com/jmarnold/EmbeddedMail/blob/master/src/EmbeddedMail/EmbeddedSmtpServer.cs#L89).

The practical reason is that each [session on disposal tries to write to its socket](https://github.com/jmarnold/EmbeddedMail/blob/master/src/EmbeddedMail/ISmtpSession.cs#L62) but `Listener` disposes "the underlying Socket" when its [`Stop` method](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcplistener.stop?view=netframework-4.7.2) is called:
> The `Stop()` method also closes the underlying `Socket`

(I am a bit confused by the use of the singular in that quote.  Does each session share the same socket?  Not exactly sure about that part.)

Exact details aside, the current order causes an `ObjectDisposedException` to be thrown.  I don't think the order that I suggested will have this problem.

**Comment by jmarnold** [comment]
It's been a while since I've looked at this one. Have you tried out your change? If so, I'm totally cool with pulling in a Pull Request and giving it a shot. Sorry for the delayed response!

**Comment by bender2k14** [comment]
I have tested it a couple times, but the problem is that the previous version didn't always throw an exception...only if there was some session to dispose.  I don't know how to ensure that there is a session when disposing.

However, we have many systems running EmbeddedMail, each of which log their behavior to a central location, and we have aggregate views of the logs.  I will monitor these logs this week as we upgrade our systems to a fork of EmbeddedMail in which I have made this change.

My plan was to wait to create a pull request until after I have this experimental evidence to add to my theoretical and practical arguments.

I thought you replied very quickly!  On a repository that hasn't been updated in three years, I was expecting no response at all.

**Comment by jmarnold** [comment]
Awesome! I'd also be totally happy to transfer over ownership of the Nuget package and repo that you don't have to maintain a fork.

**Comment by bender2k14** [comment]
That's ok.  It is easy to maintain a fork of a project that never changes :)

In our fork, we previously increased the target .Net version from 4.0 to 4.5.  I don't know why we did that, but now it is causing me difficulties back porting my fix.

One of the changes that I made is to use the overloads of the [`StreamReader`](https://docs.microsoft.com/en-us/dotnet/api/system.io.streamreader.-ctor?view=netframework-4.5#System_IO_StreamReader__ctor_System_IO_Stream_System_Text_Encoding_System_Boolean_System_Int32_System_Boolean_) and [`StreamWriter`](https://docs.microsoft.com/en-us/dotnet/api/system.io.streamwriter.-ctor?view=netframework-4.5#System_IO_StreamWriter__ctor_System_IO_Stream_System_Text_Encoding_System_Int32_System_Boolean_) constructors that take a Boolean to specify if the given stream should be closed, but [those](https://docs.microsoft.com/en-us/dotnet/api/system.io.streamreader.-ctor?view=netframework-4.0) [constructors](https://docs.microsoft.com/en-us/dotnet/api/system.io.streamwriter.-ctor?view=netframework-4.0) don't exist in .Net 4.0.

What do you think about increasing the target .Net version from 4.0 to 4.5?

The alternative I prefer is to create a `Stream` wrapper that doesn't close or dispose the provided stream when those methods are called itself.

**Comment by bender2k14** [comment]
I decided to create the PR that upgrades to .Net Framework 4.5.
